# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1340, 750)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Output_Reports/img/tinfoleak-logo-o.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_8 = QtGui.QGridLayout(Dialog)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBox_10 = QtGui.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setStyleSheet(_fromUtf8(""))
        self.groupBox_10.setTitle(_fromUtf8(""))
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rb_user = QtGui.QRadioButton(self.groupBox_10)
        self.rb_user.setChecked(True)
        self.rb_user.setAutoRepeat(False)
        self.rb_user.setObjectName(_fromUtf8("rb_user"))
        self.gridLayout_5.addWidget(self.rb_user, 1, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_10)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_5.addWidget(self.label_33, 1, 1, 1, 1)
        self.tb_username = QtGui.QLineEdit(self.groupBox_10)
        self.tb_username.setStyleSheet(_fromUtf8(""))
        self.tb_username.setObjectName(_fromUtf8("tb_username"))
        self.gridLayout_5.addWidget(self.tb_username, 1, 2, 1, 1)
        self.pb_select_users_file = QtGui.QPushButton(self.groupBox_10)
        self.pb_select_users_file.setAccessibleDescription(_fromUtf8(""))
        self.pb_select_users_file.setObjectName(_fromUtf8("pb_select_users_file"))
        self.gridLayout_5.addWidget(self.pb_select_users_file, 1, 4, 1, 1)
        self.tb_users_number = QtGui.QLineEdit(self.groupBox_10)
        self.tb_users_number.setObjectName(_fromUtf8("tb_users_number"))
        self.gridLayout_5.addWidget(self.tb_users_number, 1, 7, 1, 1)
        self.pb_last_results = QtGui.QPushButton(self.groupBox_10)
        self.pb_last_results.setObjectName(_fromUtf8("pb_last_results"))
        self.gridLayout_5.addWidget(self.pb_last_results, 1, 8, 1, 1)
        self.pb_relations = QtGui.QPushButton(self.groupBox_10)
        self.pb_relations.setObjectName(_fromUtf8("pb_relations"))
        self.gridLayout_5.addWidget(self.pb_relations, 1, 9, 1, 1)
        self.rb_place = QtGui.QRadioButton(self.groupBox_10)
        self.rb_place.setObjectName(_fromUtf8("rb_place"))
        self.gridLayout_5.addWidget(self.rb_place, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_10)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 2, 1, 1, 1)
        self.tb_place_lat = QtGui.QLineEdit(self.groupBox_10)
        self.tb_place_lat.setObjectName(_fromUtf8("tb_place_lat"))
        self.gridLayout_5.addWidget(self.tb_place_lat, 2, 2, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBox_10)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_5.addWidget(self.label_32, 2, 3, 1, 1)
        self.tb_place_lon = QtGui.QLineEdit(self.groupBox_10)
        self.tb_place_lon.setObjectName(_fromUtf8("tb_place_lon"))
        self.gridLayout_5.addWidget(self.tb_place_lon, 2, 4, 1, 2)
        self.label_34 = QtGui.QLabel(self.groupBox_10)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_5.addWidget(self.label_34, 2, 6, 1, 1)
        self.tb_place_km = QtGui.QLineEdit(self.groupBox_10)
        self.tb_place_km.setObjectName(_fromUtf8("tb_place_km"))
        self.gridLayout_5.addWidget(self.tb_place_km, 2, 7, 1, 1)
        self.rb_global_timeline = QtGui.QRadioButton(self.groupBox_10)
        self.rb_global_timeline.setObjectName(_fromUtf8("rb_global_timeline"))
        self.gridLayout_5.addWidget(self.rb_global_timeline, 3, 0, 1, 1)
        self.pb_select_users_file_3 = QtGui.QPushButton(self.groupBox_10)
        self.pb_select_users_file_3.setEnabled(False)
        self.pb_select_users_file_3.setText(_fromUtf8(""))
        self.pb_select_users_file_3.setFlat(True)
        self.pb_select_users_file_3.setObjectName(_fromUtf8("pb_select_users_file_3"))
        self.gridLayout_5.addWidget(self.pb_select_users_file_3, 3, 3, 1, 2)
        self.label_31 = QtGui.QLabel(self.groupBox_10)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_5.addWidget(self.label_31, 1, 6, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_10, 1, 0, 2, 1)
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cb_friends = QtGui.QCheckBox(self.groupBox_4)
        self.cb_friends.setObjectName(_fromUtf8("cb_friends"))
        self.gridLayout_2.addWidget(self.cb_friends, 5, 0, 1, 1)
        self.cb_kml_file_screen_name = QtGui.QCheckBox(self.groupBox_4)
        self.cb_kml_file_screen_name.setObjectName(_fromUtf8("cb_kml_file_screen_name"))
        self.gridLayout_2.addWidget(self.cb_kml_file_screen_name, 6, 6, 1, 1)
        self.cb_social_networks = QtGui.QCheckBox(self.groupBox_4)
        self.cb_social_networks.setObjectName(_fromUtf8("cb_social_networks"))
        self.gridLayout_2.addWidget(self.cb_social_networks, 1, 5, 1, 1)
        self.cb_source_apps = QtGui.QCheckBox(self.groupBox_4)
        self.cb_source_apps.setObjectName(_fromUtf8("cb_source_apps"))
        self.gridLayout_2.addWidget(self.cb_source_apps, 2, 5, 1, 1)
        self.cb_followers = QtGui.QCheckBox(self.groupBox_4)
        self.cb_followers.setObjectName(_fromUtf8("cb_followers"))
        self.gridLayout_2.addWidget(self.cb_followers, 4, 0, 1, 1)
        self.cb_mentions = QtGui.QCheckBox(self.groupBox_4)
        self.cb_mentions.setObjectName(_fromUtf8("cb_mentions"))
        self.gridLayout_2.addWidget(self.cb_mentions, 3, 4, 1, 1)
        self.cb_activity = QtGui.QCheckBox(self.groupBox_4)
        self.cb_activity.setObjectName(_fromUtf8("cb_activity"))
        self.gridLayout_2.addWidget(self.cb_activity, 0, 5, 1, 1)
        self.tb_collections_number = QtGui.QLineEdit(self.groupBox_4)
        self.tb_collections_number.setObjectName(_fromUtf8("tb_collections_number"))
        self.gridLayout_2.addWidget(self.tb_collections_number, 3, 1, 1, 1)
        self.pb_collections_view = QtGui.QPushButton(self.groupBox_4)
        self.pb_collections_view.setObjectName(_fromUtf8("pb_collections_view"))
        self.gridLayout_2.addWidget(self.pb_collections_view, 3, 2, 1, 1)
        self.cb_likes = QtGui.QCheckBox(self.groupBox_4)
        self.cb_likes.setObjectName(_fromUtf8("cb_likes"))
        self.gridLayout_2.addWidget(self.cb_likes, 1, 0, 1, 1)
        self.cb_hashtags = QtGui.QCheckBox(self.groupBox_4)
        self.cb_hashtags.setObjectName(_fromUtf8("cb_hashtags"))
        self.gridLayout_2.addWidget(self.cb_hashtags, 2, 4, 1, 1)
        self.cb_metadata = QtGui.QCheckBox(self.groupBox_4)
        self.cb_metadata.setObjectName(_fromUtf8("cb_metadata"))
        self.gridLayout_2.addWidget(self.cb_metadata, 3, 5, 1, 1)
        self.cb_collections = QtGui.QCheckBox(self.groupBox_4)
        self.cb_collections.setObjectName(_fromUtf8("cb_collections"))
        self.gridLayout_2.addWidget(self.cb_collections, 3, 0, 1, 1)
        self.pb_friends_view = QtGui.QPushButton(self.groupBox_4)
        self.pb_friends_view.setObjectName(_fromUtf8("pb_friends_view"))
        self.gridLayout_2.addWidget(self.pb_friends_view, 5, 2, 1, 1)
        self.tb_lists_number = QtGui.QLineEdit(self.groupBox_4)
        self.tb_lists_number.setObjectName(_fromUtf8("tb_lists_number"))
        self.gridLayout_2.addWidget(self.tb_lists_number, 2, 1, 1, 1)
        self.cb_account_info = QtGui.QCheckBox(self.groupBox_4)
        self.cb_account_info.setEnabled(False)
        self.cb_account_info.setCheckable(True)
        self.cb_account_info.setChecked(True)
        self.cb_account_info.setObjectName(_fromUtf8("cb_account_info"))
        self.gridLayout_2.addWidget(self.cb_account_info, 0, 0, 1, 2)
        self.pb_lists_view_2 = QtGui.QPushButton(self.groupBox_4)
        self.pb_lists_view_2.setText(_fromUtf8(""))
        self.pb_lists_view_2.setFlat(True)
        self.pb_lists_view_2.setObjectName(_fromUtf8("pb_lists_view_2"))
        self.gridLayout_2.addWidget(self.pb_lists_view_2, 0, 2, 1, 1)
        self.cb_words_frequency = QtGui.QCheckBox(self.groupBox_4)
        self.cb_words_frequency.setObjectName(_fromUtf8("cb_words_frequency"))
        self.gridLayout_2.addWidget(self.cb_words_frequency, 5, 4, 1, 1)
        self.pb_followers_view = QtGui.QPushButton(self.groupBox_4)
        self.pb_followers_view.setObjectName(_fromUtf8("pb_followers_view"))
        self.gridLayout_2.addWidget(self.pb_followers_view, 4, 2, 1, 1)
        self.tb_friends_number = QtGui.QLineEdit(self.groupBox_4)
        self.tb_friends_number.setObjectName(_fromUtf8("tb_friends_number"))
        self.gridLayout_2.addWidget(self.tb_friends_number, 5, 1, 1, 1)
        self.tb_followers_number = QtGui.QLineEdit(self.groupBox_4)
        self.tb_followers_number.setObjectName(_fromUtf8("tb_followers_number"))
        self.gridLayout_2.addWidget(self.tb_followers_number, 4, 1, 1, 1)
        self.tb_top_locations = QtGui.QLineEdit(self.groupBox_4)
        self.tb_top_locations.setObjectName(_fromUtf8("tb_top_locations"))
        self.gridLayout_2.addWidget(self.tb_top_locations, 6, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 6, 3, 1, 1)
        self.pb_lists_view = QtGui.QPushButton(self.groupBox_4)
        self.pb_lists_view.setObjectName(_fromUtf8("pb_lists_view"))
        self.gridLayout_2.addWidget(self.pb_lists_view, 2, 2, 1, 1)
        self.cb_conversations = QtGui.QCheckBox(self.groupBox_4)
        self.cb_conversations.setObjectName(_fromUtf8("cb_conversations"))
        self.gridLayout_2.addWidget(self.cb_conversations, 1, 4, 1, 1)
        self.cb_lists = QtGui.QCheckBox(self.groupBox_4)
        self.cb_lists.setObjectName(_fromUtf8("cb_lists"))
        self.gridLayout_2.addWidget(self.cb_lists, 2, 0, 1, 1)
        self.cb_protected_account = QtGui.QCheckBox(self.groupBox_4)
        self.cb_protected_account.setObjectName(_fromUtf8("cb_protected_account"))
        self.gridLayout_2.addWidget(self.cb_protected_account, 0, 4, 1, 1)
        self.cb_visited_locations = QtGui.QCheckBox(self.groupBox_4)
        self.cb_visited_locations.setObjectName(_fromUtf8("cb_visited_locations"))
        self.gridLayout_2.addWidget(self.cb_visited_locations, 6, 0, 1, 1)
        self.tb_words_frequency_number = QtGui.QLineEdit(self.groupBox_4)
        self.tb_words_frequency_number.setObjectName(_fromUtf8("tb_words_frequency_number"))
        self.gridLayout_2.addWidget(self.tb_words_frequency_number, 5, 5, 1, 1)
        self.tb_kml_filename = QtGui.QLineEdit(self.groupBox_4)
        self.tb_kml_filename.setObjectName(_fromUtf8("tb_kml_filename"))
        self.gridLayout_2.addWidget(self.tb_kml_filename, 6, 4, 1, 2)
        self.tb_likes_number = QtGui.QLineEdit(self.groupBox_4)
        self.tb_likes_number.setObjectName(_fromUtf8("tb_likes_number"))
        self.gridLayout_2.addWidget(self.tb_likes_number, 1, 1, 1, 1)
        self.cb_media = QtGui.QCheckBox(self.groupBox_4)
        self.cb_media.setObjectName(_fromUtf8("cb_media"))
        self.gridLayout_2.addWidget(self.cb_media, 4, 4, 1, 1)
        self.cb_media_download = QtGui.QCheckBox(self.groupBox_4)
        self.cb_media_download.setObjectName(_fromUtf8("cb_media_download"))
        self.gridLayout_2.addWidget(self.cb_media_download, 4, 5, 1, 1)
        self.cb_show_tweets = QtGui.QCheckBox(self.groupBox_4)
        self.cb_show_tweets.setObjectName(_fromUtf8("cb_show_tweets"))
        self.gridLayout_2.addWidget(self.cb_show_tweets, 0, 6, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_4, 4, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(Dialog)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tb_messages = QtGui.QTextEdit(self.groupBox_6)
        self.tb_messages.setEnabled(True)
        self.tb_messages.setReadOnly(True)
        self.tb_messages.setObjectName(_fromUtf8("tb_messages"))
        self.gridLayout_6.addWidget(self.tb_messages, 1, 0, 1, 1)
        self.tbl_targets_analyzed = QtGui.QTableWidget(self.groupBox_6)
        self.tbl_targets_analyzed.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.tbl_targets_analyzed.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbl_targets_analyzed.setRowCount(0)
        self.tbl_targets_analyzed.setObjectName(_fromUtf8("tbl_targets_analyzed"))
        self.tbl_targets_analyzed.setColumnCount(4)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_targets_analyzed.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_targets_analyzed.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_targets_analyzed.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_targets_analyzed.setHorizontalHeaderItem(3, item)
        self.gridLayout_6.addWidget(self.tbl_targets_analyzed, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 0, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_6, 5, 0, 1, 2)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 6, 0, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(Dialog)
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setFlat(False)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_35 = QtGui.QLabel(self.groupBox_11)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_7.addWidget(self.label_35, 0, 0, 1, 1)
        self.tb_tweets_number = QtGui.QLineEdit(self.groupBox_11)
        self.tb_tweets_number.setObjectName(_fromUtf8("tb_tweets_number"))
        self.gridLayout_7.addWidget(self.tb_tweets_number, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(201, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 2, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBox_11)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_7.addWidget(self.label_36, 1, 0, 1, 1)
        self.tb_report_filename = QtGui.QLineEdit(self.groupBox_11)
        self.tb_report_filename.setObjectName(_fromUtf8("tb_report_filename"))
        self.gridLayout_7.addWidget(self.tb_report_filename, 1, 1, 1, 2)
        self.cb_file_screen_name = QtGui.QCheckBox(self.groupBox_11)
        self.cb_file_screen_name.setObjectName(_fromUtf8("cb_file_screen_name"))
        self.gridLayout_7.addWidget(self.cb_file_screen_name, 1, 3, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_11, 2, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_8.addWidget(self.buttonBox, 6, 1, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_8.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_27 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_8.addWidget(self.label_27, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 3, 0, 1, 1)
        self.frame = QtGui.QFrame(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(271, 56))
        self.frame.setMaximumSize(QtCore.QSize(540, 56))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, -7, 261, 71))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.frame, 0, 1, 2, 1, QtCore.Qt.AlignRight)
        self.groupBox_5 = QtGui.QGroupBox(Dialog)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem1 = QtGui.QSpacerItem(62, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.tb_not_include_words = QtGui.QLineEdit(self.groupBox_5)
        self.tb_not_include_words.setObjectName(_fromUtf8("tb_not_include_words"))
        self.gridLayout.addWidget(self.tb_not_include_words, 3, 1, 1, 4)
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 3, 0, 1, 1)
        self.tb_edate = QtGui.QDateEdit(self.groupBox_5)
        self.tb_edate.setDate(QtCore.QDate(2018, 1, 1))
        self.tb_edate.setCalendarPopup(True)
        self.tb_edate.setObjectName(_fromUtf8("tb_edate"))
        self.gridLayout.addWidget(self.tb_edate, 1, 1, 1, 1)
        self.tb_etime = QtGui.QTimeEdit(self.groupBox_5)
        self.tb_etime.setTime(QtCore.QTime(23, 59, 59))
        self.tb_etime.setCalendarPopup(False)
        self.tb_etime.setObjectName(_fromUtf8("tb_etime"))
        self.gridLayout.addWidget(self.tb_etime, 1, 4, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(62, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        self.tb_include_words = QtGui.QLineEdit(self.groupBox_5)
        self.tb_include_words.setObjectName(_fromUtf8("tb_include_words"))
        self.gridLayout.addWidget(self.tb_include_words, 2, 1, 1, 4)
        self.tb_stime = QtGui.QTimeEdit(self.groupBox_5)
        self.tb_stime.setObjectName(_fromUtf8("tb_stime"))
        self.gridLayout.addWidget(self.tb_stime, 0, 4, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 1, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 0, 0, 1, 1)
        self.tb_sdate = QtGui.QDateEdit(self.groupBox_5)
        self.tb_sdate.setDate(QtCore.QDate(2018, 1, 1))
        self.tb_sdate.setCalendarPopup(True)
        self.tb_sdate.setObjectName(_fromUtf8("tb_sdate"))
        self.gridLayout.addWidget(self.tb_sdate, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 0, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 4, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.groupBox_5)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 7, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBox_5)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout.addWidget(self.label_38, 6, 0, 1, 1)
        self.tb_source_app = QtGui.QLineEdit(self.groupBox_5)
        self.tb_source_app.setText(_fromUtf8(""))
        self.tb_source_app.setObjectName(_fromUtf8("tb_source_app"))
        self.gridLayout.addWidget(self.tb_source_app, 4, 1, 1, 3)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_9.setTitle(_fromUtf8(""))
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.rb_RT_yes = QtGui.QRadioButton(self.groupBox_9)
        self.rb_RT_yes.setGeometry(QtCore.QRect(0, 8, 51, 20))
        self.rb_RT_yes.setObjectName(_fromUtf8("rb_RT_yes"))
        self.rb_RT_no = QtGui.QRadioButton(self.groupBox_9)
        self.rb_RT_no.setGeometry(QtCore.QRect(50, 8, 51, 20))
        self.rb_RT_no.setObjectName(_fromUtf8("rb_RT_no"))
        self.rb_RT_all = QtGui.QRadioButton(self.groupBox_9)
        self.rb_RT_all.setGeometry(QtCore.QRect(100, 8, 51, 20))
        self.rb_RT_all.setChecked(True)
        self.rb_RT_all.setObjectName(_fromUtf8("rb_RT_all"))
        self.gridLayout.addWidget(self.groupBox_9, 6, 1, 1, 2)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.rb_media_yes = QtGui.QRadioButton(self.groupBox_7)
        self.rb_media_yes.setGeometry(QtCore.QRect(0, 5, 51, 20))
        self.rb_media_yes.setObjectName(_fromUtf8("rb_media_yes"))
        self.rb_media_no = QtGui.QRadioButton(self.groupBox_7)
        self.rb_media_no.setGeometry(QtCore.QRect(50, 5, 51, 20))
        self.rb_media_no.setObjectName(_fromUtf8("rb_media_no"))
        self.rb_media_all = QtGui.QRadioButton(self.groupBox_7)
        self.rb_media_all.setGeometry(QtCore.QRect(100, 5, 51, 20))
        self.rb_media_all.setChecked(True)
        self.rb_media_all.setObjectName(_fromUtf8("rb_media_all"))
        self.gridLayout.addWidget(self.groupBox_7, 7, 1, 1, 2)
        self.pb_reset_filters = QtGui.QPushButton(self.groupBox_5)
        self.pb_reset_filters.setObjectName(_fromUtf8("pb_reset_filters"))
        self.gridLayout.addWidget(self.pb_reset_filters, 7, 4, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.rb_sourceapp_yes = QtGui.QRadioButton(self.groupBox_8)
        self.rb_sourceapp_yes.setGeometry(QtCore.QRect(0, 5, 51, 20))
        self.rb_sourceapp_yes.setChecked(True)
        self.rb_sourceapp_yes.setObjectName(_fromUtf8("rb_sourceapp_yes"))
        self.rb_sourceapp_no = QtGui.QRadioButton(self.groupBox_8)
        self.rb_sourceapp_no.setGeometry(QtCore.QRect(50, 5, 51, 20))
        self.rb_sourceapp_no.setObjectName(_fromUtf8("rb_sourceapp_no"))
        self.gridLayout.addWidget(self.groupBox_8, 4, 4, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_5, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "tinfoleak v2.4", None))
        self.rb_user.setText(_translate("Dialog", "User", None))
        self.label_33.setText(_translate("Dialog", "@", None))
        self.pb_select_users_file.setText(_translate("Dialog", "File", None))
        self.tb_users_number.setText(_translate("Dialog", "50", None))
        self.pb_last_results.setText(_translate("Dialog", "Last file", None))
        self.pb_relations.setText(_translate("Dialog", "Relations", None))
        self.rb_place.setText(_translate("Dialog", "Place", None))
        self.label_8.setText(_translate("Dialog", "Lat", None))
        self.label_32.setText(_translate("Dialog", "Lon", None))
        self.label_34.setText(_translate("Dialog", "Km", None))
        self.tb_place_km.setText(_translate("Dialog", "0.5", None))
        self.rb_global_timeline.setText(_translate("Dialog", "Timeline", None))
        self.label_31.setText(_translate("Dialog", "Users", None))
        self.cb_friends.setText(_translate("Dialog", "Friends", None))
        self.cb_kml_file_screen_name.setText(_translate("Dialog", "User name", None))
        self.cb_social_networks.setText(_translate("Dialog", "Social networks", None))
        self.cb_source_apps.setText(_translate("Dialog", "Source applications", None))
        self.cb_followers.setText(_translate("Dialog", "Followers", None))
        self.cb_mentions.setText(_translate("Dialog", "Mentions", None))
        self.cb_activity.setText(_translate("Dialog", "User activity", None))
        self.tb_collections_number.setText(_translate("Dialog", "50", None))
        self.pb_collections_view.setText(_translate("Dialog", "View", None))
        self.cb_likes.setText(_translate("Dialog", "Likes", None))
        self.cb_hashtags.setText(_translate("Dialog", "Hashtags", None))
        self.cb_metadata.setText(_translate("Dialog", "Metadata", None))
        self.cb_collections.setText(_translate("Dialog", "Collections", None))
        self.pb_friends_view.setText(_translate("Dialog", "View", None))
        self.tb_lists_number.setText(_translate("Dialog", "50", None))
        self.cb_account_info.setText(_translate("Dialog", "Account information", None))
        self.cb_words_frequency.setText(_translate("Dialog", "Words frequency", None))
        self.pb_followers_view.setText(_translate("Dialog", "View", None))
        self.tb_friends_number.setText(_translate("Dialog", "50", None))
        self.tb_followers_number.setText(_translate("Dialog", "50", None))
        self.tb_top_locations.setText(_translate("Dialog", "50", None))
        self.label_16.setText(_translate("Dialog", "File name", None))
        self.pb_lists_view.setText(_translate("Dialog", "View", None))
        self.cb_conversations.setText(_translate("Dialog", "Conversations", None))
        self.cb_lists.setText(_translate("Dialog", "Lists", None))
        self.cb_protected_account.setText(_translate("Dialog", "Protected account", None))
        self.cb_visited_locations.setText(_translate("Dialog", "Locations", None))
        self.tb_words_frequency_number.setText(_translate("Dialog", "50", None))
        self.tb_kml_filename.setText(_translate("Dialog", "tinfoleak.kml", None))
        self.tb_likes_number.setText(_translate("Dialog", "50", None))
        self.cb_media.setText(_translate("Dialog", "Multimedia", None))
        self.cb_media_download.setText(_translate("Dialog", "Download multimedia", None))
        self.cb_show_tweets.setText(_translate("Dialog", "Show tweets", None))
        self.tb_messages.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        item = self.tbl_targets_analyzed.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Date time", None))
        item = self.tbl_targets_analyzed.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "ToA", None))
        item = self.tbl_targets_analyzed.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Information", None))
        item = self.tbl_targets_analyzed.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Additional", None))
        self.label.setText(_translate("Dialog", "Messages", None))
        self.label_26.setText(_translate("Dialog", "Latest Targets Analyzed", None))
        self.label_2.setText(_translate("Dialog", "Created by: Vicente Aguilera Diaz. Twitter: @VAguileraDiaz", None))
        self.label_35.setText(_translate("Dialog", "Number of tweets", None))
        self.tb_tweets_number.setText(_translate("Dialog", "50", None))
        self.label_36.setText(_translate("Dialog", "Output file", None))
        self.tb_report_filename.setText(_translate("Dialog", "tinfoleak.html", None))
        self.cb_file_screen_name.setText(_translate("Dialog", "User name", None))
        self.label_7.setText(_translate("Dialog", "Target of Analysis", None))
        self.label_27.setText(_translate("Dialog", "Filters", None))
        self.label_9.setText(_translate("Dialog", "Operations", None))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/tinfoleak/img/tinfoleak-logo-interface.png\"/></p></body></html>", None))
        self.label_22.setText(_translate("Dialog", "Don\'t include words", None))
        self.tb_edate.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd", None))
        self.tb_etime.setDisplayFormat(_translate("Dialog", "HH:mm:ss", None))
        self.tb_stime.setDisplayFormat(_translate("Dialog", "HH:mm:ss", None))
        self.label_20.setText(_translate("Dialog", "End time", None))
        self.label_19.setText(_translate("Dialog", "End date", None))
        self.label_17.setText(_translate("Dialog", "Start date", None))
        self.tb_sdate.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd", None))
        self.label_18.setText(_translate("Dialog", "Start time", None))
        self.label_21.setText(_translate("Dialog", "Include words", None))
        self.label_25.setText(_translate("Dialog", "Source application", None))
        self.label_37.setText(_translate("Dialog", "Mutimedia", None))
        self.label_38.setText(_translate("Dialog", "Retweet", None))
        self.rb_RT_yes.setText(_translate("Dialog", "Yes", None))
        self.rb_RT_no.setText(_translate("Dialog", "No", None))
        self.rb_RT_all.setText(_translate("Dialog", "All", None))
        self.rb_media_yes.setText(_translate("Dialog", "Yes", None))
        self.rb_media_no.setText(_translate("Dialog", "No", None))
        self.rb_media_all.setText(_translate("Dialog", "All", None))
        self.pb_reset_filters.setText(_translate("Dialog", "Reset", None))
        self.rb_sourceapp_yes.setText(_translate("Dialog", "Yes", None))
        self.rb_sourceapp_no.setText(_translate("Dialog", "No", None))

import mylogo_rc
